### ISSUE TITLE
[Improve][Doc] Explain the process of extending an MQ in DataProxy

### ISSUE THREAD

**Issue by liangyepianzhou** [apache/inlong-website#508]
### Description

This article is aimed at DataProxy developers, trying to explain as fully as possible the process of extending an MQ dataProxy, strive to eliminate developer confusion and make it easy for dataprxoy to extend new MQ.

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
duplicated with https://github.com/apache/inlong-website/issues/651
