### ISSUE TITLE
[Bug][Search]: Update the key for algolia

### ISSUE THREAD

**Issue by Chever-John** [apache/inlong-website#564]
### What happened

Enhanced fix for #387

This is an issue aiming to fix the search function. After checking, I found that the apikey given to me by algolia had changed, which caused the search to behave abnormally from time to time.

### What you expected to happen

I was able to search inlong's documentation properly through algolia's search engine.

### How to reproduce

The fact that you go searching now will give you a partial chance of reproducing the problem.

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Chever-John** [comment]
@bluewang 
I need to remind you that it seems like my fix didn't work. I guess you can choose plan B now.

**Comment by bluewang** [comment]
> @bluewang I need to remind you that it seems like my fix didn't work. I guess you can choose plan B now.

Ok. I will choose the next one. Is the key in the code applied for by your private email?

**Comment by Chever-John** [comment]
@bluewang 
Here's the deal, you just need to communicate with algolia by email. They will tell you how to request an `appid` for an open-source project.
