### ISSUE TITLE
[Feature][Doc] Translate http report guide

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong-website#627]
### Description

Translate HTTP report guide：

https://inlong.apache.org/docs/next/sdk/dataproxy-sdk/http

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by allendang001** [comment]
please assign to me?
