### ISSUE TITLE
[Feature][Doc] Add docs for TubeMQ c++/python sdk.

### ISSUE THREAD

**Issue by xuehuanran** [apache/inlong-website#659]
### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VirendraYadav1234** [comment]
I want to work on this issue please assign me this issue

**Comment by dockerzhang** [comment]
@VirendraYadav1234 thanks, but https://github.com/apache/inlong-website/pull/660 has completed this issue.
