### ISSUE TITLE
[Feature][Doc] Add document for dirty data archive

### ISSUE THREAD

**Issue by yunqingmoswu** [apache/inlong-website#675]
### Description

Add document for dirty data archive

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VirendraYadav1234** [comment]
I want to work on this issue please assign me this issue
