### ISSUE TITLE
[Improve][Doc] Modify polardbx-sql link

### ISSUE THREAD

**Issue by hnrainll** [apache/inlong-website#760]
### Description

I found the link to polardbx in the documentation as https://github.com/ApsaraDB/galaxysql. However, it has been modified to
https://github.com/polardb/polardbx-sql and the modified link expresses its meaning better, although the previous link still redirects to the later one.

![WX20230524-102553](https://github.com/apache/inlong-website/assets/1780095/8df59d2b-71d4-4d10-b9e5-c09613c3a5fb)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hnrainll** [comment]
I'm considering how much value the modification has and would like to hear your opinions.

**Comment by dockerzhang** [comment]
@hnrainll nice to have. If the official repo link changes, using the formal address is better.

**Comment by hnrainll** [comment]
Happy, next I'm going to try to commit the code in the inlong project.
